"""Short-side position adjustment signal helpers."""

from pandas import Series

def short_buyback_entry_v2(
  strategy, last_candle: Series, previous_candle: Series, slice_profit: float, is_derisk: bool
) -> float:
  if (last_candle["protections_short_global"] == True) and (
    (last_candle["enter_short"] == True)
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 80.0)
      and (last_candle["RSI_3_15m"] < 70.0)
      and (last_candle["RSI_3_1h"] < 70.0)
      and (last_candle["RSI_3_4h"] < 70.0)
      and (last_candle["AROOND_14"] < 25.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      # and (last_candle["ROC_9_4h"] > -20.0)
      # and (last_candle["ROC_9_4h"] < 40.0)
      # and (last_candle["ROC_9_1d"] > -20.0)
      # and (last_candle["ROC_9_1d"] < 50.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["STOCHRSIk_14_14_3_3_15m"] > 80.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_1h"] < 30.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_4h"] < 30.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      # and (last_candle["close"] < (last_candle["low_min_24_4h"] * 1.20))
      and (last_candle["close"] > (last_candle["EMA_16"] * 1.120))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 85.0)
      and (last_candle["RSI_3_1h"] < 85.0)
      and (last_candle["RSI_3_4h"] < 85.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      # and (last_candle["ROC_2_1d"] > -10.0)
      # and (last_candle["ROC_9_1h"] > -10.0)
      # and (last_candle["ROC_9_4h"] > -10.0)
      and (last_candle["ROC_9_1d"] < 5.0)
      and (last_candle["EMA_12"] > last_candle["EMA_26"])
      and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.020))
      and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      and (last_candle["ROC_2_1d"] < 5.0)
      and (last_candle["ROC_9_1h"] < 5.0)
      and (last_candle["ROC_9_4h"] < 5.0)
      and (last_candle["ROC_9_1d"] < 10.0)
      # and (last_candle["ROC_9_4h"] < 40.0)
      # and (last_candle["ROC_9_1d"] < 50.0)
      and (last_candle["AROOND_14_15m"] < 25.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      # and (last_candle["close"] < (last_candle["low_min_24_4h"] * 1.20))
      and (last_candle["close"] > (last_candle["EMA_12"] * 1.020))
    )
    or (
      (last_candle["RSI_14"] < 64.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      # and (last_candle["ROC_2_1d"] > -5.0)
      and (last_candle["ROC_9_1h"] < 5.0)
      and (last_candle["ROC_9_4h"] < 5.0)
      and (last_candle["ROC_9_1d"] < 5.0)
      and (last_candle["STOCHRSIk_14_14_3_3_1h"] > 20.0)
      and (last_candle["STOCHRSIk_14_14_3_3_4h"] > 30.0)
      # and (last_candle["close"] > (last_candle["close_max_48"] * 0.90))
      # and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      # and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["close"] > (last_candle["EMA_26"] * 1.040))
      and (last_candle["close"] > (last_candle["BBU_20_2.0"] * 1.001))
    )
  ):
    return True

  return False

def short_grind_entry_v2(
  strategy, last_candle: Series, previous_candle: Series, slice_profit: float, is_derisk: bool
) -> float:
  if (last_candle["protections_short_global"] == True) and (
    (last_candle["enter_short"] == True)
    or (
      (last_candle["RSI_14"] > 54.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 85.0)
      and (last_candle["RSI_3_1h"] < 85.0)
      and (last_candle["RSI_3_4h"] < 85.0)
      and (last_candle["ROC_2_1h"] < 10.0)
      and (last_candle["ROC_2_4h"] < 10.0)
      and (last_candle["ROC_2_1d"] < 10.0)
      and (last_candle["ROC_9_1h"] < 25.0)
      and (last_candle["ROC_9_4h"] < 25.0)
      and (last_candle["ROC_9_1d"] < 25.0)
      # and (last_candle["ROC_9_1d"] < 40.0)
      and (last_candle["AROOND_14"] < 25.0)
      # and (last_candle["STOCHRSIk_14_14_3_3"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_15m"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_1h"] < 30.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_4h"] < 30.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["close"] > (last_candle["high_max_24_4h"] * 0.85))
      and (last_candle["close"] > (last_candle["EMA_16"] * 1.032))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 85.0)
      and (last_candle["RSI_3_1h"] < 85.0)
      and (last_candle["RSI_3_4h"] < 85.0)
      # and (last_candle["RSI_3_1d"] > 15.0)
      and (last_candle["ROC_2_1h"] < 10.0)
      and (last_candle["ROC_2_4h"] < 10.0)
      # and (last_candle["ROC_2_1d"] > -10.0)
      and (last_candle["ROC_9_1h"] < 10.0)
      and (last_candle["ROC_9_4h"] < 10.0)
      and (last_candle["ROC_9_1d"] < 30.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 50.0)
      and (last_candle["EMA_12"] > last_candle["EMA_26"])
      and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.020))
      and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      and (last_candle["ROC_2_1d"] < 5.0)
      and (last_candle["ROC_9_1h"] < 10.0)
      and (last_candle["ROC_9_4h"] < 10.0)
      and (last_candle["ROC_9_1d"] < 10.0)
      # and (last_candle["ROC_9_4h"] < 40.0)
      # and (last_candle["ROC_9_1d"] < 50.0)
      and (last_candle["AROOND_14_15m"] < 25.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      # and (last_candle["close"] < (last_candle["low_min_24_4h"] * 1.20))
      and (last_candle["close"] > (last_candle["EMA_12"] * 1.020))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["ROC_2_1h"] < 10.0)
      and (last_candle["ROC_2_4h"] < 10.0)
      and (last_candle["ROC_2_1d"] < 10.0)
      # and (last_candle["ROC_9_1h"] > -10.0)
      # and (last_candle["ROC_9_4h"] > -10.0)
      # and (last_candle["ROC_9_1d"] > -10.0)
      and (last_candle["AROOND_14"] < 25.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["close"] > (last_candle["EMA_26"] * 1.038))
      and (last_candle["close"] > (last_candle["BBU_20_2.0"] * 1.0))
    )
    or (
      (last_candle["RSI_14"] > 65.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      # and (last_candle["RSI_3_1d"] > 10.0)
      and (last_candle["ROC_2_1h"] < 10.0)
      and (last_candle["ROC_2_4h"] < 10.0)
      and (last_candle["ROC_2_1d"] < 10.0)
      and (last_candle["ROC_9_1h"] < 10.0)
      and (last_candle["ROC_9_4h"] < 10.0)
      # and (last_candle["ROC_9_1d"] > -10.0)
      and (last_candle["AROOND_14"] < 25.0)
      # and (last_candle["AROONU_14_15m"] < 25.0)
      # and (last_candle["STOCHRSIk_14_14_3_3"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_15m"] < 20.0)
      # and (last_candle["close"] > (last_candle["close_max_48"] * 0.90))
      # and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      # and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["close"] > (last_candle["high_max_12_4h"] * 0.80))
      and (last_candle["close"] > (last_candle["EMA_9"] * 1.032))
      and (last_candle["close"] > (last_candle["EMA_20"] * 1.020))
    )
    or (
      (last_candle["RSI_14"] > 65.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3"] > 60.0)
      # and (last_candle["RSI_4"] < 40.0)
      and (last_candle["RSI_3_15m"] < 85.0)
      # and (last_candle["RSI_3_1h"] > 20.0)
      # and (last_candle["RSI_3_4h"] > 20.0)
      # and (last_candle["RSI_3_1d"] > 20.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      # and (last_candle["ROC_2_1d"] > -5.0)
      and (last_candle["ROC_9_1h"] < 10.0)
      and (last_candle["ROC_9_4h"] < 10.0)
      # and (last_candle["ROC_9_1d"] > -10.0)
      and (last_candle["AROOND_14"] < 25.0)
      # and (last_candle["AROONU_14_15m"] < 25.0)
      # and (last_candle["STOCHRSIk_14_14_3_3"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_15m"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_1h"] < 50.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_4h"] < 50.0)
      # and (last_candle["close"] > (last_candle["close_max_48"] * 0.90))
      # and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      # and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["RSI_20"] > previous_candle["RSI_20"])
      and (last_candle["close"] > (last_candle["SMA_16"] * 1.045))
      # and (last_candle["close"] < (last_candle["EMA_20"] * 0.980))
    )
    or (
      (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      and (last_candle["ROC_9_1h"] < 5.0)
      and (last_candle["ROC_9_4h"] < 5.0)
      and (last_candle["WILLR_14"] > -50.0)
      # and (last_candle["AROONU_14"] < 25.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["WILLR_84_1h"] > -30.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_1h"] < 40.0)
      and (last_candle["close"] < (last_candle["high_max_24_4h"] * 0.77))
      and (last_candle["BBB_20_2.0_1h"] > 12.0)
      and (last_candle["close_min_48"] <= (last_candle["close"] * 0.90))
    )
    or (
      (last_candle["RSI_3"] > 70.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 95.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      # and (last_candle["ROC_2_1h"] > -5.0)
      # and (last_candle["ROC_2_4h"] > -5.0)
      # and (last_candle["ROC_9_1h"] > -5.0)
      # and (last_candle["ROC_9_4h"] > -5.0)
      and (last_candle["ROC_9_1d"] < 30.0)
      # and (last_candle["STOCHRSIk_14_14_3_3"] < 20.0)
      # and (last_candle["close"] < (last_candle["low_min_24_4h"] * 1.50))
      and (last_candle["EMA_12"] > last_candle["EMA_26"])
      and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.034))
      and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
    )
    or (
      (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 75.0)
      and (last_candle["RSI_3_1h"] < 70.0)
      and (last_candle["close"] > (last_candle["low_min_24_4h"] * 1.10))
      and (last_candle["close"] > (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["close_max_12"] * 0.92))
    )
    or (
      (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 95.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["RSI_14"] > (last_candle["RSI_14_1h"] + 45.0))
    )
    or (
      (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["close"] > (last_candle["SMA_30"] * 1.022))
      and (last_candle["close"] > (last_candle["BBU_20_2.0"] * 1.0))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 70.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.15))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.20))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.33))
      and (last_candle["close"] > (last_candle["high_max_12_4h"] * 0.75))
      and (last_candle["EMA_12"] > last_candle["EMA_26"])
      and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.018))
      and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
    )
    or (
      (last_candle["RSI_3"] < 95.0)
      and (previous_candle["SMA_9"] > previous_candle["SMA_21"])
      and (last_candle["SMA_9"] < last_candle["SMA_21"])
      and (last_candle["close"] > (last_candle["EMA_100"] * 1.016))
      and (last_candle["RSI_3_1h"] < 80.0)
      and (last_candle["RSI_3_4h"] < 80.0)
    )
    or (
      (slice_profit > 0.12)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_14"] > 60.0)
      and (last_candle["AROOND_14"] < 25.0)
      and (last_candle["AROOND_14_15m"] < 30.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["STOCHRSIk_14_14_3_3_15m"] > 70.0)
      and (last_candle["RSI_14_1h"] > 50.0)
      and (last_candle["RSI_14_4h"] > 50.0)
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["close"] > (last_candle["EMA_12"] * 1.001))
      and (last_candle["close"] > (last_candle["BBL_20_2.0"] * 1.004))
    )
  ):
    return True

  return False

def short_buyback_exit_v2(
  strategy, last_candle: Series, previous_candle: Series, slice_profit: float, is_derisk: bool
) -> float:
  if (
    (last_candle["RSI_3"] < 1.0)
    or (last_candle["RSI_14"] < 30.0)
    or (last_candle["WILLR_14"] < -99.9)
    or (last_candle["STOCHRSIk_14_14_3_3"] > 5.0)
    or (last_candle["close"] < (last_candle["BBL_20_2.0"] * 0.99))
    or ((last_candle["RSI_3"] < 10.0) and (last_candle["RSI_14"] > 50.0))
  ):
    return True

  return False

def short_grind_exit_v2(
  strategy, last_candle: Series, previous_candle: Series, slice_profit: float, is_derisk: bool
) -> float:
  if (
    (last_candle["RSI_3"] < 1.0)
    or (last_candle["RSI_14"] < 30.0)
    or (last_candle["WILLR_14"] < -99.9)
    or (last_candle["STOCHRSIk_14_14_3_3"] < 5.0)
    or (last_candle["close"] < (last_candle["BBL_20_2.0"] * 0.99))
    or ((last_candle["RSI_3"] < 10.0) and (last_candle["RSI_14"] > 50.0))
  ):
    return True

  return False

# Short Grinding Adjust Trade Position v3
# ---------------------------------------------------------------------------------------------

def short_grind_entry_v3(
  strategy, last_candle: Series, previous_candle: Series, slice_profit: float, is_derisk: bool
) -> float:
  if (last_candle["protections_short_global"] == True) and (
    (last_candle["enter_short"] == True)
    or (
      (last_candle["RSI_14"] > 54.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 85.0)
      and (last_candle["RSI_3_1h"] < 85.0)
      and (last_candle["RSI_3_4h"] < 85.0)
      and (last_candle["ROC_2_1h"] < 10.0)
      and (last_candle["ROC_2_4h"] < 10.0)
      and (last_candle["ROC_2_1d"] < 10.0)
      and (last_candle["ROC_9_1h"] < 25.0)
      and (last_candle["ROC_9_4h"] < 25.0)
      and (last_candle["ROC_9_1d"] < 25.0)
      # and (last_candle["ROC_9_1d"] < 40.0)
      and (last_candle["AROOND_14"] < 25.0)
      # and (last_candle["STOCHRSIk_14_14_3_3"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_15m"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_1h"] < 30.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_4h"] < 30.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["close"] > (last_candle["high_max_24_4h"] * 0.85))
      and (last_candle["close"] > (last_candle["EMA_16"] * 1.012))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 85.0)
      and (last_candle["RSI_3_1h"] < 85.0)
      and (last_candle["RSI_3_4h"] < 85.0)
      # and (last_candle["RSI_3_1d"] > 15.0)
      and (last_candle["ROC_2_1h"] < 10.0)
      and (last_candle["ROC_2_4h"] < 10.0)
      # and (last_candle["ROC_2_1d"] > -10.0)
      and (last_candle["ROC_9_1h"] < 10.0)
      and (last_candle["ROC_9_4h"] < 10.0)
      and (last_candle["ROC_9_1d"] < 30.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 50.0)
      and (last_candle["EMA_12"] > last_candle["EMA_26"])
      and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.020))
      and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      and (last_candle["ROC_2_1d"] < 5.0)
      and (last_candle["ROC_9_1h"] < 10.0)
      and (last_candle["ROC_9_4h"] < 10.0)
      and (last_candle["ROC_9_1d"] < 10.0)
      # and (last_candle["ROC_9_4h"] < 40.0)
      # and (last_candle["ROC_9_1d"] < 50.0)
      and (last_candle["AROOND_14_15m"] < 25.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      # and (last_candle["close"] < (last_candle["low_min_24_4h"] * 1.20))
      and (last_candle["close"] > (last_candle["EMA_12"] * 1.020))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["ROC_2_1h"] < 10.0)
      and (last_candle["ROC_2_4h"] < 10.0)
      and (last_candle["ROC_2_1d"] < 10.0)
      # and (last_candle["ROC_9_1h"] > -10.0)
      # and (last_candle["ROC_9_4h"] > -10.0)
      # and (last_candle["ROC_9_1d"] > -10.0)
      and (last_candle["AROOND_14"] < 25.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["close"] > (last_candle["EMA_26"] * 1.018))
      and (last_candle["close"] > (last_candle["BBU_20_2.0"] * 1.0))
    )
    or (
      (last_candle["RSI_14"] > 65.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      # and (last_candle["RSI_3_1d"] > 10.0)
      and (last_candle["ROC_2_1h"] < 10.0)
      and (last_candle["ROC_2_4h"] < 10.0)
      and (last_candle["ROC_2_1d"] < 10.0)
      and (last_candle["ROC_9_1h"] < 10.0)
      and (last_candle["ROC_9_4h"] < 10.0)
      # and (last_candle["ROC_9_1d"] > -10.0)
      and (last_candle["AROOND_14"] < 25.0)
      # and (last_candle["AROONU_14_15m"] < 25.0)
      # and (last_candle["STOCHRSIk_14_14_3_3"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_15m"] < 20.0)
      # and (last_candle["close"] > (last_candle["close_max_48"] * 0.90))
      # and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      # and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["close"] > (last_candle["high_max_12_4h"] * 0.80))
      and (last_candle["close"] > (last_candle["EMA_9"] * 1.032))
      and (last_candle["close"] > (last_candle["EMA_20"] * 1.020))
    )
    or (
      (last_candle["RSI_14"] > 65.0)
      and (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3"] > 60.0)
      # and (last_candle["RSI_4"] < 40.0)
      and (last_candle["RSI_3_15m"] < 85.0)
      # and (last_candle["RSI_3_1h"] > 20.0)
      # and (last_candle["RSI_3_4h"] > 20.0)
      # and (last_candle["RSI_3_1d"] > 20.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      # and (last_candle["ROC_2_1d"] > -5.0)
      and (last_candle["ROC_9_1h"] < 10.0)
      and (last_candle["ROC_9_4h"] < 10.0)
      # and (last_candle["ROC_9_1d"] > -10.0)
      and (last_candle["AROOND_14"] < 25.0)
      # and (last_candle["AROONU_14_15m"] < 25.0)
      # and (last_candle["STOCHRSIk_14_14_3_3"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_15m"] < 20.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_1h"] < 50.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_4h"] < 50.0)
      # and (last_candle["close"] > (last_candle["close_max_48"] * 0.90))
      # and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.18))
      # and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.25))
      and (last_candle["RSI_20"] > previous_candle["RSI_20"])
      and (last_candle["close"] > (last_candle["SMA_16"] * 1.045))
      # and (last_candle["close"] < (last_candle["EMA_20"] * 0.980))
    )
    or (
      (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["ROC_2_1h"] < 5.0)
      and (last_candle["ROC_2_4h"] < 5.0)
      and (last_candle["ROC_9_1h"] < 5.0)
      and (last_candle["ROC_9_4h"] < 5.0)
      and (last_candle["WILLR_14"] > -50.0)
      # and (last_candle["AROONU_14"] < 25.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["WILLR_84_1h"] > -30.0)
      # and (last_candle["STOCHRSIk_14_14_3_3_1h"] < 40.0)
      and (last_candle["close"] < (last_candle["high_max_24_4h"] * 0.77))
      and (last_candle["BBB_20_2.0_1h"] > 12.0)
      and (last_candle["close_min_48"] <= (last_candle["close"] * 0.90))
    )
    or (
      (last_candle["RSI_3"] > 70.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 95.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      # and (last_candle["ROC_2_1h"] > -5.0)
      # and (last_candle["ROC_2_4h"] > -5.0)
      # and (last_candle["ROC_9_1h"] > -5.0)
      # and (last_candle["ROC_9_4h"] > -5.0)
      and (last_candle["ROC_9_1d"] < 30.0)
      # and (last_candle["STOCHRSIk_14_14_3_3"] < 20.0)
      # and (last_candle["close"] < (last_candle["low_min_24_4h"] * 1.50))
      and (last_candle["EMA_12"] > last_candle["EMA_26"])
      and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.034))
      and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
    )
    or (
      (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 75.0)
      and (last_candle["RSI_3_1h"] < 70.0)
      and (last_candle["close"] > (last_candle["low_min_24_4h"] * 1.10))
      and (last_candle["close"] > (last_candle["close_min_48"] * 1.10))
      and (last_candle["close"] < (last_candle["close_max_12"] * 0.92))
    )
    or (
      (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 95.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["RSI_14"] > (last_candle["RSI_14_1h"] + 45.0))
    )
    or (
      (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["close"] > (last_candle["SMA_30"] * 1.022))
      and (last_candle["close"] > (last_candle["BBU_20_2.0"] * 1.0))
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["RSI_3_1d"] < 90.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 70.0)
      and (last_candle["close"] < (last_candle["close_min_48"] * 1.15))
      and (last_candle["close"] < (last_candle["low_min_6_1h"] * 1.20))
      and (last_candle["close"] < (last_candle["low_min_12_1h"] * 1.33))
      and (last_candle["close"] > (last_candle["high_max_12_4h"] * 0.75))
      and (last_candle["EMA_12"] > last_candle["EMA_26"])
      and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.018))
      and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
    )
    or (
      (last_candle["RSI_3"] < 95.0)
      and (previous_candle["SMA_9"] > previous_candle["SMA_21"])
      and (last_candle["SMA_9"] < last_candle["SMA_21"])
      and (last_candle["close"] > (last_candle["EMA_100"] * 1.016))
      and (last_candle["RSI_3_1h"] < 80.0)
      and (last_candle["RSI_3_4h"] < 80.0)
    )
    or (
      (slice_profit > 0.12)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["RSI_14"] > 60.0)
      and (last_candle["AROOND_14"] < 25.0)
      and (last_candle["AROOND_14_15m"] < 30.0)
      and (last_candle["STOCHRSIk_14_14_3_3"] > 80.0)
      and (last_candle["STOCHRSIk_14_14_3_3_15m"] > 70.0)
      and (last_candle["RSI_14_1h"] > 50.0)
      and (last_candle["RSI_14_4h"] > 50.0)
    )
    or (
      (last_candle["RSI_14"] > 64.0)
      and (last_candle["RSI_3"] < 95.0)
      and (last_candle["RSI_3_1h"] < 90.0)
      and (last_candle["RSI_3_4h"] < 90.0)
      and (last_candle["close"] > (last_candle["EMA_12"] * 1.001))
      and (last_candle["close"] > (last_candle["BBL_20_2.0"] * 1.004))
    )
  ):
    return True

  return False

def short_rebuy_entry_v3(
  strategy, last_candle: Series, previous_candle: Series, slice_profit: float, is_derisk: bool
) -> float:
  if (last_candle["protections_short_global"] == True) and (
    (last_candle["enter_short"] == True)
    or (
      (last_candle["RSI_3"] < 90.0)
      and (last_candle["RSI_3_15m"] < 90.0)
      and (last_candle["AROOND_14"] < 30.0)
      and (last_candle["AROOND_14_15m"] < 30.0)
      and (last_candle["close"] > (last_candle["EMA_26"] * 1.012))
    )
  ):
    return True

  return False

# Short Grinding Adjust Trade Position
# ---------------------------------------------------------------------------------------------

def short_grind_entry(
  strategy, last_candle: Series, previous_candle: Series, slice_profit: float, is_derisk: bool
) -> float:
  if (
    (last_candle["protections_short_global"] == True)
    and (last_candle["protections_short_rebuy"] == True)
    and (last_candle["global_protections_short_pump"] == True)
    and (last_candle["global_protections_short_dump"] == True)
    and (
      (last_candle["enter_short"] == True)
      or (
        (last_candle["RSI_14"] > 64.0)
        and (last_candle["RSI_3"] < 90.0)
        and (last_candle["RSI_3_15m"] < 90.0)
        and (last_candle["AROOND_14"] < 25.0)
        and (last_candle["STOCHRSIk_14_14_3_3_1h"] > 30.0)
        and (last_candle["STOCHRSIk_14_14_3_3_4h"] > 30.0)
        and (last_candle["close"] > (last_candle["EMA_16"] * 1.020))
      )
      or (
        (last_candle["RSI_14"] > 64.0)
        and (last_candle["RSI_3_15m"] < 95.0)
        and (last_candle["RSI_3_1h"] < 95.0)
        and (last_candle["RSI_3_4h"] < 95.0)
        and (last_candle["EMA_12"] > last_candle["EMA_26"])
        and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.030))
        and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
      )
      or (
        (last_candle["RSI_14"] > 64.0)
        and (last_candle["RSI_3"] < 95.0)
        and (last_candle["RSI_3_15m"] < 90.0)
        and (last_candle["RSI_3_1h"] < 90.0)
        and (last_candle["RSI_3_4h"] < 90.0)
        and (last_candle["EMA_12"] > last_candle["EMA_26"])
        and ((last_candle["EMA_12"] - last_candle["EMA_26"]) > (last_candle["open"] * 0.020))
        and ((previous_candle["EMA_12"] - previous_candle["EMA_26"]) > (last_candle["open"] / 100.0))
      )
      or (
        (last_candle["RSI_14"] > 64.0)
        and (last_candle["RSI_3"] < 84.0)
        and (last_candle["AROOND_14_15m"] < 25.0)
        and (last_candle["close"] > (last_candle["EMA_12"] * 1.016))
      )
      or (
        (last_candle["RSI_14"] > 64.0)
        and (last_candle["RSI_3_15m"] < 90.0)
        and (last_candle["RSI_3_1h"] < 90.0)
        and (last_candle["RSI_3_4h"] < 90.0)
        and (last_candle["AROONU_14_1h"] < last_candle["AROOND_14_1h"])
        and (last_candle["AROONU_14_4h"] < last_candle["AROOND_14_4h"])
        and (last_candle["close"] > (last_candle["EMA_26"] * 1.022))
        and (last_candle["close"] > (last_candle["BBL_20_2.0"] * 1.001))
      )
      or (
        (last_candle["RSI_14"] > 64.0)
        and (last_candle["RSI_3_1h"] < 80.0)
        and (last_candle["RSI_3_4h"] < 80.0)
        and (last_candle["RSI_14_1h"] > 20.0)
        and (last_candle["RSI_14_4h"] > 40.0)
        and (last_candle["AROONU_14"] < last_candle["AROOND_14"])
        and (previous_candle["AROONU_14"] > previous_candle["AROOND_14"])
      )
      or (
        (last_candle["RSI_14"] > 64.0)
        and (last_candle["RSI_3_15m"] < 85.0)
        and (last_candle["RSI_3_1h"] < 80.0)
        and (last_candle["RSI_3_4h"] < 80.0)
        and (last_candle["RSI_14_1h"] > 20.0)
        and (last_candle["RSI_14_4h"] > 40.0)
        and (last_candle["KST_10_15_20_30_10_10_10_15"] < last_candle["KSTs_9"])
        and (previous_candle["KST_10_15_20_30_10_10_10_15"] > previous_candle["KSTs_9"])
      )
      or (
        is_derisk
        and (last_candle["RSI_3"] < 80.0)
        and (last_candle["RSI_3_15m"] < 80.0)
        and (last_candle["RSI_3_1h"] < 80.0)
        and (last_candle["RSI_3_4h"] < 80.0)
        and (last_candle["RSI_14"] > 64.0)
        and (last_candle["AROOND_14"] < 25.0)
        and (last_candle["AROOND_14_15m"] < 25.0)
        and (last_candle["STOCHRSIk_14_14_3_3_15m"] > 50.0)
        and (last_candle["close"] > (last_candle["EMA_20"] * 1.020))
      )
    )
  ):
    return True

  return False

# Short Grinding Adjust Trade Position No De-Risk
# ---------------------------------------------------------------------------------------------

